workflows:
  ios-app-store:
    name: iOS App Store Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios
      vars:
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
      xcode: 16.1
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true

    scripts:
      - name: Set up code signing
        script: |
          set -e
          # Decode and install provisioning profile
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > /tmp/profile.mobileprovision
          PROFILE_UUID=$(grep UUID -A1 -a /tmp/profile.mobileprovision | grep -io "[-A-F0-9]\{36\}")
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp /tmp/profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"

          # Read profile display name (can contain spaces) and persist QUOTED in $CM_ENV
          PROFILE_NAME=$(security cms -D -i /tmp/profile.mobileprovision | plutil -extract Name raw -)
          {
            echo "export PROFILE_NAME=\"${PROFILE_NAME}\""
            echo "export PROFILE_UUID=\"${PROFILE_UUID}\""
          } >> "$CM_ENV"

          # Import certificate & make codesign identity available
          echo "$P12_BASE64" | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import /tmp/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

          CERTIFICATE_NAME=$(security find-identity -v -p codesigning build.keychain | grep "iPhone Distribution" | head -1 | sed -n 's/.*"\(.*\)".*/\1/p')
          if [ -z "$CERTIFICATE_NAME" ]; then
            CERTIFICATE_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Apple Distribution" | head -1 | sed -n 's/.*"\(.*\)".*/\1/p')
          fi
          echo "Found certificate: $CERTIFICATE_NAME"
          echo "export CERTIFICATE_NAME=\"${CERTIFICATE_NAME}\"" >> "$CM_ENV"

      - name: Install CocoaPods dependencies
        script: |
          set -e
          if [ -f "Podfile" ]; then
            pod repo update
            pod install
          fi

      - name: Select workspace or project
        script: |
          set -e
          if [ -f "Unity-iPhone.xcworkspace" ]; then
            echo "Detected workspace. Building with CocoaPods integration."
            {
              echo 'export XCODE_WORKSPACE="Unity-iPhone.xcworkspace"'
              echo 'export BUILD_USES_PODS=true'
            } >> "$CM_ENV"
          else
            echo "No workspace found. Building the Xcode project."
            echo 'export BUILD_USES_PODS=false' >> "$CM_ENV"
          fi

      - name: Increment build number
        script: |
          set -e
          cd Unity-iPhone.xcodeproj/..
          agvtool new-version -all $(($(app-store-connect get-latest-build-number "$APP_STORE_ID") + 1))

      - name: Create export options
        script: |
          cat > "$HOME/export_options.plist" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>JQ8ZF3V63Z</string>
            <key>uploadSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Relax non-modular warnings (Pods)
        script: |
          set -e
          if [ -f "Podfile" ]; then
            pod install
            # BSD sed on macOS requires '' after -i
            find Pods -name "*.xcconfig" -type f -exec sed -i '' 's/-Werror=non-modular-include-in-framework-module//g' {} \;
            find Pods -name "*.xcconfig" -type f -exec sed -i '' 's/-Wnon-modular-include-in-framework-module//g' {} \;
            echo "Relaxed non-modular include flags in Pods xcconfigs"
          fi

      - name: Update Xcode project settings (signing & warnings)
        script: |
          set -e
          gem install xcodeproj --no-document || true
          ruby <<'RUBY'
          require 'xcodeproj'
          project = Xcodeproj::Project.open('Unity-iPhone.xcodeproj')

          # App target signing
          main = project.targets.find { |t| t.name == 'Unity-iPhone' }
          main.build_configurations.each do |c|
            c.build_settings['CODE_SIGN_STYLE'] = 'Manual'
            c.build_settings['CODE_SIGN_IDENTITY'] = ENV['CERTIFICATE_NAME']
            c.build_settings['DEVELOPMENT_TEAM'] = 'JQ8ZF3V63Z'
            c.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ENV['PROFILE_NAME']
          end

          # UnityFramework warnings
          fw = project.targets.find { |t| t.name == 'UnityFramework' }
          fw.build_configurations.each do |c|
            c.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
            c.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
            c.build_settings['CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'] = 'NO'
            c.build_settings['OTHER_CFLAGS'] = [
              '-Wno-error=non-modular-include-in-framework-module',
              '-Wno-non-modular-include-in-framework-module'
            ]
          end

          project.save
          RUBY

      - name: Define UNITY_VERSION_* (fix UnityTrampolineConfigure.h)
        script: |
          set -e
          # Use your Unity version string directly:
          UNITY_VERSION_STRING="2022.3.621f2"
          echo "Using Unity version: $UNITY_VERSION_STRING"

          # Extract VER, MAJ, MIN numerically (VER=year, MAJ=minor, MIN=patch digits)
          UNITY_VER=$(echo "$UNITY_VERSION_STRING" | awk -F. '{print $1}')
          UNITY_MAJ=$(echo "$UNITY_VERSION_STRING" | awk -F. '{print $2}')
          UNITY_MIN=$(echo "$UNITY_VERSION_STRING" | awk -F. '{print $3}' | sed 's/[^0-9].*$//')

          gem install xcodeproj --no-document || true
          ruby <<'RUBY'
          require 'xcodeproj'
          project = Xcodeproj::Project.open('Unity-iPhone.xcodeproj')
          ver = ENV['UNITY_VER'] || '2022'
          maj = ENV['UNITY_MAJ'] || '3'
          min = ENV['UNITY_MIN'] || '0'

          project.targets.each do |t|
            t.build_configurations.each do |c|
              defs = c.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || []
              defs = [defs] if defs.is_a?(String)
              defs.reject! { |d| d =~ /^UNITY_VERSION_(VER|MAJ|MIN)=/ }
              defs << "UNITY_VERSION_VER=#{ver}"
              defs << "UNITY_VERSION_MAJ=#{maj}"
              defs << "UNITY_VERSION_MIN=#{min}"
              c.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
            end
          end

          project.save
          RUBY

      - name: Strip leftover Google Ads link references
        script: |
          set -e
          # If the project still contains references to GoogleMobileAds / UMP, strip them so the linker won't search for missing frameworks.
          if [ -f "Unity-iPhone.xcodeproj/project.pbxproj" ]; then
            PBX="Unity-iPhone.xcodeproj/project.pbxproj"
            # Remove build file / file ref / framework search path entries mentioning these frameworks
            sed -i '' '/GoogleMobileAds/d' "$PBX"
            sed -i '' '/GoogleUserMessagingPlatform/d' "$PBX"
            echo "Removed GoogleMobileAds & GoogleUserMessagingPlatform references from project.pbxproj"
          fi

      - name: Build IPA
        script: |
          set -e
          # reload env (quoted exports)
          if [ -f "$CM_ENV" ]; then
            # shellcheck disable=SC1090
            source "$CM_ENV"
          fi
          echo "BUILD_USES_PODS=$BUILD_USES_PODS"
          if [ "${BUILD_USES_PODS}" = "true" ]; then
            echo "Building from workspace (CocoaPods detected)"
            xcode-project build-ipa \
              --workspace "$XCODE_WORKSPACE" \
              --scheme "$XCODE_SCHEME" \
              --export-options-plist "$HOME/export_options.plist"
          else
            echo "Building from project (no Pods detected)"
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --export-options-plist "$HOME/export_options.plist"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - joshtimallendev@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
