workflows:
  ios-app-store:
    name: iOS App Store Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - ios
      vars:
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    
    scripts:
      - name: Set up code signing
        script: |
          set -e
          
          echo $PROVISION_PROFILE_BASE64 | base64 --decode > /tmp/profile.mobileprovision
          PROFILE_UUID=$(grep UUID -A1 -a /tmp/profile.mobileprovision | grep -io "[-A-F0-9]\{36\}")
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision
          
          PROFILE_NAME=$(security cms -D -i /tmp/profile.mobileprovision | plutil -extract Name raw -)
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          
          echo $P12_BASE64 | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security list-keychains -s build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain
          security import /tmp/certificate.p12 -k build.keychain -P $P12_PASSWORD -T /usr/bin/codesign -T /usr/bin/security
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          
          CERTIFICATE_NAME=$(security find-identity -v -p codesigning build.keychain | grep "iPhone Distribution" | head -1 | sed -n 's/.*"\(.*\)".*/\1/p')
          if [ -z "$CERTIFICATE_NAME" ]; then
            CERTIFICATE_NAME=$(security find-identity -v -p codesigning build.keychain | grep "Apple Distribution" | head -1 | sed -n 's/.*"\(.*\)".*/\1/p')
          fi
          echo "CERTIFICATE_NAME=$CERTIFICATE_NAME" >> $CM_ENV
          echo "Found certificate: $CERTIFICATE_NAME"
      
      - name: Install CocoaPods dependencies
        script: |
          set -e
          
          if [ -f "Podfile" ]; then
            echo "Found Podfile, recreating it..."
            cp Podfile Podfile.backup
            
            echo "platform :ios, '13.0'" > Podfile
            echo "" >> Podfile
            echo "target 'Unity-iPhone' do" >> Podfile
            echo "  pod 'Google-Mobile-Ads-SDK'" >> Podfile
            echo "  pod 'GoogleUserMessagingPlatform'" >> Podfile
            echo "end" >> Podfile
            
            echo "Running pod install..."
            pod install
            
            echo "Checking for workspace files..."
            ls -la | grep -i workspace || echo "No workspace files found"
            ls -la | grep -i xcworkspace || echo "No xcworkspace files found"
            find . -name "*.xcworkspace" -maxdepth 2 || echo "Find command found nothing"
            
            if [ -f "Unity-iPhone.xcworkspace" ]; then
              echo "✅ Workspace created successfully"
            elif [ -d "Unity-iPhone.xcworkspace" ]; then
              echo "✅ Workspace is a DIRECTORY (correct!)"
            else
              echo "❌ ERROR: Workspace not created!"
              echo "Current directory contents:"
              ls -la
              exit 1
            fi
            
            find Pods -name "*.xcconfig" -type f -exec sed -i '' 's/-Werror=non-modular-include-in-framework-module//g' {} \;
            find Pods -name "*.xcconfig" -type f -exec sed -i '' 's/-Wnon-modular-include-in-framework-module//g' {} \;
          else
            echo "❌ ERROR: No Podfile found!"
            exit 1
          fi
      
      - name: Update Xcode project with signing
        script: |
          set -e
          gem install xcodeproj || true
          
          ruby <<'RUBY'
          require 'xcodeproj'
          project = Xcodeproj::Project.open('Unity-iPhone.xcodeproj')
          
          target = project.targets.find { |t| t.name == 'Unity-iPhone' }
          target.build_configurations.each do |config|
            config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
            config.build_settings['CODE_SIGN_IDENTITY'] = ENV['CERTIFICATE_NAME']
            config.build_settings['DEVELOPMENT_TEAM'] = 'JQ8ZF3V63Z'
            config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = ENV['PROFILE_NAME']
          end
          
          unity_framework = project.targets.find { |t| t.name == 'UnityFramework' }
          unity_framework.build_configurations.each do |config|
            config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
            config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
            config.build_settings['CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'] = 'NO'
            
            other_cflags = config.build_settings['OTHER_CFLAGS'] || []
            other_cflags = [other_cflags] if other_cflags.is_a?(String)
            other_cflags.delete_if { |flag| flag.to_s.include?('non-modular-include-in-framework-module') }
            other_cflags << '-Wno-error=non-modular-include-in-framework-module'
            other_cflags << '-Wno-non-modular-include-in-framework-module'
            config.build_settings['OTHER_CFLAGS'] = other_cflags
          end
          
          project.save
          RUBY
      
      - name: Create export options
        script: |
          cat > $HOME/export_options.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>JQ8ZF3V63Z</string>
            <key>uploadSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF
      
      - name: Build IPA
        script: |
          set -e
          
          # Always use workspace if it exists (CocoaPods creates it)
          if [ -d "Unity-iPhone.xcworkspace" ]; then
            echo "Building with workspace (CocoaPods)"
            xcode-project build-ipa \
              --workspace "Unity-iPhone.xcworkspace" \
              --scheme "$XCODE_SCHEME" \
              --export-options-plist "$HOME/export_options.plist"
          else
            echo "ERROR: Unity-iPhone.xcworkspace not found. CocoaPods installation may have failed."
            echo "Building with project as fallback..."
            xcode-project build-ipa \
              --project "$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME" \
              --export-options-plist "$HOME/export_options.plist"
          fi
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    
    publishing:
      email:
        recipients:
          - joshtimallendev@gmail.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true