workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    environment:
      vars:
        XCODE_VERSION: "16.4"
        UNITY_VERSION: "2022.3.60f1"
        PROJECT_NAME: "Unity-iPhone"
        SCHEME: "Unity-iPhone"
        APP_BUNDLE_ID: "com.Josh-TimAllen.AthleticGames"
        APP_NAME: "AthleticGames"
        DEVELOPMENT_TEAM: "JQ8ZF3V63Z"
        PROVISIONING_PROFILE_SPECIFIER: "Athletic Games Profile"
        CODE_SIGN_IDENTITY: "Apple Distribution: Josh-Tim Allen (JQ8ZF3V63Z)"
        BUILD_DIR: "$CM_BUILD_DIR/ios"
      xcode: 16.4
      cocoapods: default
      node: 20
    scripts:
      - name: 🧹 Clean previous builds
        script: |
          rm -rf "$BUILD_DIR" || true
          mkdir -p "$BUILD_DIR"
          echo "Cleaned build directory at $BUILD_DIR"

      - name: ⚙️ Check build settings
        script: |
          echo "Checking build settings for $PROJECT_NAME..."
          xcodebuild -project "$PROJECT_NAME.xcodeproj" -scheme "$SCHEME" -showBuildSettings | tee build_settings.txt

      - name: 🏗️ Build IPA
        script: |
          echo "Starting Xcode archive for $APP_NAME..."
          xcodebuild \
            -project "$PROJECT_NAME.xcodeproj" \
            -scheme "$SCHEME" \
            -archivePath "$BUILD_DIR/xcarchive/$PROJECT_NAME.xcarchive" \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            CODE_SIGN_STYLE=Manual \
            COMPILER_INDEX_STORE_ENABLE=NO \
            archive

      - name: 📦 Export IPA
        script: |
          echo "Creating export options plist..."
          cat <<EOF > exportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${APP_BUNDLE_ID}</key>
              <string>${PROVISIONING_PROFILE_SPECIFIER}</string>
            </dict>
            <key>teamID</key>
            <string>${DEVELOPMENT_TEAM}</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          echo "Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath "$BUILD_DIR/xcarchive/$PROJECT_NAME.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$BUILD_DIR/ipa"

      - name: 🧾 Verify IPA
        script: |
          echo "Contents of exported IPA directory:"
          ls -lah "$BUILD_DIR/ipa"

      - name: 🧠 Print summary
        script: |
          echo "✅ Build complete!"
          echo "Xcode Version: $XCODE_VERSION"
          echo "Unity Version: $UNITY_VERSION"
          echo "Team: $DEVELOPMENT_TEAM"
          echo "Provisioning Profile: $PROVISIONING_PROFILE_SPECIFIER"
          echo "Code Sign Identity: $CODE_SIGN_IDENTITY"
          echo "Output IPA location: $BUILD_DIR/ipa"

    artifacts:
      - "$BUILD_DIR/ipa/*.ipa"
      - "$BUILD_DIR/xcarchive/*.xcarchive"
      - "build_settings.txt"

    publishing:
      email:
        recipients:
          - "your@email.com"
        notify:
          success: true
          failure: true
